"""Compare the committed contract snapshot with what a live platform advertises.

``contracts/platform-tools.snapshot.json`` records every tool the pinned platform image offered
when it was taken; ``compare`` says which tools appeared, disappeared or changed shape since. The
snapshot is regenerated by ``make snapshot`` and never edited by hand.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ContractDiff:
    """Per-name deltas between two ``tools/list`` snapshots."""

    added: tuple[str, ...]
    removed: tuple[str, ...]
    changed: tuple[str, ...]

    @property
    def is_empty(self) -> bool:
        return not (self.added or self.removed or self.changed)


def normalize(snapshot: dict[str, Any]) -> dict[str, Any]:
    """Rewrite a snapshot so two of them can be compared without false differences.

    Tools are sorted by name, because the platform may list them in any order, and only the six
    fields ``_tool_view`` keeps are retained — the rest is server-side detail that changes freely.
    """
    tools = snapshot.get("tools") or []
    normalized: list[dict[str, Any]] = []
    for tool in sorted(tools, key=lambda t: t["name"]):
        normalized.append(_tool_view(tool))
    return {"tools": normalized}


def compare(committed: dict[str, Any], live: dict[str, Any]) -> ContractDiff:
    """What changed going from the committed snapshot to what the live platform advertises.

    Pass both through ``normalize`` first, or ordering alone will show up as a change.
    """
    committed_by_name = _index(committed)
    live_by_name = _index(live)

    added = tuple(sorted(set(live_by_name) - set(committed_by_name)))
    removed = tuple(sorted(set(committed_by_name) - set(live_by_name)))
    changed = tuple(
        sorted(
            name
            for name in set(committed_by_name) & set(live_by_name)
            if committed_by_name[name] != live_by_name[name]
        )
    )
    return ContractDiff(added=added, removed=removed, changed=changed)


def _index(snapshot: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {t["name"]: dict(t) for t in snapshot.get("tools") or []}


def _tool_view(tool: dict[str, Any]) -> dict[str, Any]:
    """The six fields worth snapshotting, leaving out metadata the server changes on its own.

    ``required_scope`` and ``is_idempotent`` are read with ``.get`` and an explicit default rather
    than ``or``: ``None`` and ``False`` are real answers here, and ``or`` would replace them.
    """
    return {
        "name": tool["name"],
        "description": tool.get("description", ""),
        "inputSchema": tool.get("inputSchema") or {},
        "outputSchema": tool.get("outputSchema") or {},
        "required_scope": tool.get("required_scope"),
        "is_idempotent": tool.get("is_idempotent", False),
    }
